os: linux
language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: false
node_js:
  - '11'
  - '10'
  - '8'

jobs:
  include:
    - stage: test
      name: 'Unit tests'
      script: npm run test:prod
    - script: npm run lint
      name: 'Linting'
    - script: npm run build
      name: 'Build'
    - stage: release
      node_js: lts/*
      if: branch = master
      deploy:
        provider: script
        cleanup: false
        script: npm run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
