language: node_js

node_js:
  - lts/*
script: npm run test:prod && npm run build
notifications:
  email: false
node_js:
- '10'
before_script:
- git version
after_success:
- npm run report-coverage
- npm run semantic-release
- npm run deploy-docs
